src/apps/cuentas/urls.py
from django.urls import path

from . import views

app_name = 'cuentas'


urlpatterns = [
    path('nuevo/', views.Nuevo.as_view(), name='nuevo'),
    path('detalle/', views.CuentaDetalles.as_view(), name='detalle'),
    path('cuenta/', views.IngresoDineroView.as_view(), name='ingresar_dinero'),
    path('cuentas_frecuentes/agregar/', views.AgregarCuentaFrecuente.as_view(), name='agregar_cuenta_frecuente'),
    path('cuentas_frecuentes/', views.ListaCuentasFrecuentes.as_view(), name='lista_cuentas_frecuentes'),
    path('cuentas-frecuentes/eliminar/<int:pk>/', views.EliminarCuentaFrecuente.as_view(), name='eliminar_cuenta_frecuente'),
]

src/apps/motivos/urls.py
from django.urls import path

from . import views

app_name = 'motivo'


urlpatterns = [
    path('nuevo/', views.NuevoMotivo.as_view(), name='nuevo'),
    path('', views.MotivoListView.as_view(), name='motivo_list'),
    path('crear/', views.MotivoCreateView.as_view(), name='motivo_create'),
    path('editar/<int:pk>/', views.MotivoUpdateView.as_view(), name='motivo_update'),
    path('eliminar/<int:pk>/', views.MotivoDeleteView.as_view(), name='motivo_delete'),
]

src/apps/transacciones/urls.py
from django.urls import path

from . import views

app_name = 'transaccion'


urlpatterns = [
    path('nueva/', views.NuevaTransaccion.as_view(), name='nueva'),
    path('comprobante/<int:pk>/', views.ComprobanteTransaccion.as_view(), name='comprobante'),
    path('transacciones/', views.ListaTransacciones.as_view(), name='lista'),
]

src/apps/usuarios/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'


urlpatterns = [
    path('nuevo/', views.Nuevo.as_view(), name='nuevo'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('usuario/<int:id>/', views.UsuarioDetalles.as_view(), name='detalle'),
    path('usuario/editar/', views.UsuarioUpdate.as_view(), name='editar'),

    path('buscar/', views.buscar_usuarios, name='buscar_usuarios'),
    path('admin/usuarios/', views.AdminUserListView.as_view(), name='admin_user_list'),
    path('admin/<int:user_id>/toggle-active/', views.toggle_user_active, name='toggle_user_active'),
    path('admin/<int:pk>/editar/', views.EditarUsuarioView.as_view(), name='editar_usuario'),
    path('admin/<int:pk>/detalle/', views.DetalleUsuarioView.as_view(), name='detalle_usuario'),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as views_django
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.BaseTemplateView.as_view(), name='inicio'),

    path('login/', views.LoginTempletaView.as_view(), name='login'),
    path('logout/', views_django.logout_then_login, name='logout'),

    path('cuentas/', include('apps.cuentas.urls')),
    path('motivos/', include('apps.motivos.urls')),
    path('transacciones/', include('apps.transacciones.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>
        {% block title_block%}
            Inicio
        {% endblock title_block %}
        | MEBU
    </title>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/source-sans-3@5.0.12/index.css" integrity="sha256-tXJfXfp6Ewt1ilPzLDtQnJV4hclT9XuaZUKyUvmyr+Q=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/overlayscrollbars@2.3.0/styles/overlayscrollbars.min.css" integrity="sha256-dSokZseQNT08wYEWiz5iLI8QPlKxG+TswNRD8k35cpg=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.min.css" integrity="sha256-Qsx5lrStHZyR9REqhUF8iQt73X06c8LGIUPzpOhwRrI=" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/adminlte.css' %}" type="text/css">
    <link rel="icon" type="image/x-icon" href="{% static 'ecom_logo.ico' %}">


    {% block css_extra %}
    {% endblock css_extra %}

</head>

<body class="layout-fixed sidebar-expand-lg bg-body-tertiary">
    <div class="app-wrapper">

        {% include 'base/header.html' %}

        {% include 'base/left-side-menu.html' %}

        <main class="app-main">

            {% include 'base/content_header.html' %}
            
            <div class="app-content">
                <div class="container-fluid">
                    
                    {% block content %}
                    {% endblock content %}
                    
                </div>
            </div>
            
        </main>

        {% include 'base/footer.html' %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/overlayscrollbars@2.3.0/browser/overlayscrollbars.browser.es6.min.js" integrity="sha256-H2VM7BKda+v2Z4+DRy69uknwxjyDRhszjXFhsL4gD3w=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha256-whL0tQWoY1Ku1iskqPFvmZ+CHsvmRWx/PIoEvIeWh4I=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha256-YMa+wAM6QkVyz999odX7lPRxkoYAan8suedu4k2Zur8=" crossorigin="anonymous"></script>
    
    <script src="{% static 'js/adminlte.js' %}"></script>

    {% block js_extra %}
    {% endblock js_extra %}

</body>

src/templates/base/content_header.html
{% load static %}

<div class="app-content-header">
    <div class="container-fluid">
        <div class="row">
            
            <div class="col-sm-6">
                <h3 class="mb-0">{{ titulo }}</h3>
            </div>
            
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-end">
                    <li class="breadcrumb-item"><a href="{% url 'inicio' %}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        {{ subtitulo }}
                    </li>
                </ol>
            </div>

        </div>
    </div>
</div>

src/templates/base/footer.html
{% load static %}

<footer class="app-footer">
    <div class="float-end d-none d-sm-inline">Bootcamp Python</div>
    <strong>
        Copyright &copy; 2024&nbsp;
        <a href="https://github.com/Dihue" class="text-decoration-none">Dihue</a>.
    </strong>
    All rights reserved.
</footer>

src/templates/base/header.html
{% load static %}

<nav class="app-header navbar navbar-expand bg-body">
    <div class="container-fluid">

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-lte-toggle="sidebar" href="#" role="button">
                    <i class="bi bi-list"></i>
                </a>
            </li>
        </ul>
        
        <ul class="navbar-nav ms-auto">
            <li class="nav-item dropdown user-menu">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                    {% if user.is_authenticated %}
                        {% if user.foto_perfil %}
                            <img src="{{ user.foto_perfil.url }}" class="user-image rounded-circle shadow" alt="User Image">
                        {% else %}
                            <img src="{% static 'assets/img/user.png' %}" class="user-image rounded-circle shadow" alt="User Image">
                        {% endif %}
                        <span class="d-none d-md-inline">{{ user.username }}</span>
                    {% else %}
                        <img src="{% static 'assets/img/user.png' %}" class="user-image rounded-circle shadow" alt="User Image">
                    {% endif %}
                </a>
                <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
                    <li class="user-header text-bg-primary">
                        {% if user.foto_perfil %}
                            <img src="{{ user.foto_perfil.url }}" class="rounded-circle shadow" alt="User Image">
                        {% else %}
                            <img src="{% static 'assets/img/user.png' %}" class="rounded-circle shadow" alt="User Image">
                        {% endif %}
                            <p>
                            {% if user.is_authenticated %}
                                {{ user.get_full_name }}
                            {% else %}
                                <p><a href="{% url 'login' %}">Iniciar sesión</a></p>
                            {% endif %}

                            <small>{ ROL }</small>
                        </p>
                    </li>
                    {% if user.is_superuser %}
                        <li class="user-body">
                            <div class="row">
                                <div class="col-4 text-center">
                                    <a href="{% url 'admin:index' %}">Admin Django</a>
                                </div>
                            </div>
                        </li>
                    {% endif %}

                    <form action="{% url 'logout' %}" method="POST">{% csrf_token %}

                        <li class="user-footer"> 
                            <button href="#" class="btn btn-default btn-flat">Salir</button> 
                        </li>


                        <li class="nav-item">
                            <button class="nav-link d-flex align-items-center gap-2" type="submit">
                                <svg class="bi">
                                    <use xlink:href="#door-closed"></use>
                                </svg>
                                Salir
                            </button>
                        </li>
                    </form>
                </ul>
            </li>
        </ul>
    </div>
</nav>

src/templates/base/left-side-menu.html
{% load static %}

<aside class="app-sidebar bg-body-secondary shadow" data-bs-theme="dark">
    
    <div class="sidebar-brand">
        <a href="{% url 'inicio' %}" class="brand-link">
            <img src="{% static 'assets/img/AdminLTELogo.png' %}" alt="Logo App Vac" class="brand-image opacity-75 shadow">
            <span class="brand-text fw-light">M.E.B.U.</span>
        </a>
    </div>

    <div class="sidebar-wrapper">
        <nav class="mt-2">
            <ul class="nav sidebar-menu flex-column" data-lte-toggle="treeview" role="menu" data-accordion="false">
                
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'usuarios:nuevo' %}" class="nav-link">
                            <i class="nav-icon bi bi-person-vcard-fill"></i>
                            <p>Registrarse</p>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon bi bi-person-fill"></i>
                            <p>
                                Usuario
                                <i class="nav-arrow bi bi-chevron-right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            
                            <li class="nav-item">
                                <a href="{% url 'usuarios:detalle' user.id %}" class="nav-link">
                                    <i class="nav-icon bi bi-person-fill-gear"></i>
                                    <p>Detalles</p>
                                </a>
                            </li>
                            
                        </ul>
                    </li>
                
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon bi bi-wallet2"></i>
                        <p>
                            Cuenta
                            <i class="nav-arrow bi bi-chevron-right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        {% if not request.user.cuenta %}
                            <li class="nav-item">
                                <a href="{% url 'cuentas:nuevo' %}" class="nav-link">
                                    <i class="nav-icon bi bi-circle"></i>
                                    <p>Nuevo</p>
                                </a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a href="{% url 'cuentas:ingresar_dinero' %}" class="nav-link">
                                <i class="nav-icon bi bi-cash-stack"></i>
                                <p>Ingresar dinero</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'cuentas:detalle' %}" class="nav-link">
                                <i class="nav-icon bi bi-card-checklist"></i>
                                <p>Detalle</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon bi bi-bank"></i>
                        <p>
                            Transferencia
                            <i class="nav-arrow bi bi-chevron-right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'transaccion:nueva' %}" class="nav-link">
                                <i class="nav-icon bi bi-arrow-left-right"></i>
                                <p>Nueva</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'transaccion:lista' %}" class="nav-link">
                                <i class="nav-icon bi bi-card-list"></i>
                                <p>Lista</p>
                            </a>
                        </li>
                    </ul>
                </li>
                {% endif %}
                
                {% if user.is_authenticated and es_admin %}
                    <li class="nav-header">ADMINISTRACION</li>
                    
                    <li class="nav-item">
                        <a href="{% url 'usuarios:admin_user_list' %}" class="nav-link">
                            <i class="nav-icon bi bi-people-fill"></i>
                            <p>Lista de Usuarios</p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon bi bi-clipboard"></i>
                            <p>
                                Motivo
                                <i class="nav-arrow bi bi-chevron-right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'motivo:nuevo' %}" class="nav-link">
                                    <i class="nav-icon bi bi-clipboard-plus"></i>
                                    <p>Nuevo</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'motivo:motivo_create' %}" class="nav-link">
                                    <i class="nav-icon bi bi-clipboard-check"></i>
                                    <p>Crear</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'motivo:motivo_list' %}" class="nav-link">
                                    <i class="nav-icon bi bi-clipboard-check"></i>
                                    <p>Lista</p>
                                </a>
                            </li>
                            
                        </ul>
                    </li>
                {% endif %}

                <li class="nav-header">DOCUMENTACION</li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon bi bi-question-circle-fill"></i>
                        <p>FAQ</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon bi bi-patch-check-fill"></i>
                        <p>License</p>
                    </a>
                </li>

            </ul>
        </nav>
    </div>
</aside>