src/apps/usuarios/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'


urlpatterns = [
    path('nuevo/', views.Nuevo.as_view(), name='nuevo'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('usuario/<int:id>/', views.UsuarioDetalles.as_view(), name='detalle'),
    path('usuario/editar/', views.UsuarioUpdate.as_view(), name='editar'),

    path('buscar/', views.buscar_usuarios, name='buscar_usuarios'),
    path('admin/usuarios/', views.AdminUserListView.as_view(), name='admin_user_list'),
    path('admin/<int:user_id>/toggle-active/', views.toggle_user_active, name='toggle_user_active'),
    path('admin/<int:pk>/editar/', views.EditarUsuarioView.as_view(), name='editar_usuario'),
    path('admin/<int:pk>/detalle/', views.DetalleUsuarioView.as_view(), name='detalle_usuario'),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as views_django
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.BaseTemplateView.as_view(), name='inicio'),

    path('login/', views.LoginTempletaView.as_view(), name='login'),
    path('logout/', views_django.logout_then_login, name='logout'),

    path('cuentas/', include('apps.cuentas.urls')),
    path('motivos/', include('apps.motivos.urls')),
    path('transacciones/', include('apps.transacciones.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    dni = models.IntegerField(unique=True, null=True)
    es_admin = models.BooleanField(default=False)
    foto_perfil = models.ImageField(upload_to='avatars/', null=True, blank=True)
    

    def __str__(self):
        return f'{self.username}'

src/apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Usuario


class FormUsuario(UserCreationForm):

    class Meta:
        model = Usuario
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'dni',
            'foto_perfil'
        ]
    

class UsuarioFilterForm(forms.Form):
    q = forms.CharField(
        required=False,
        label="Buscar",
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Por nombre o apellido',
        })
    )


class EditarUsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'email', 'dni', 'is_active']
        widgets = {
            'is_active': forms.CheckboxInput(),
        }

src/apps/usuarios/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from .forms import FormUsuario, UsuarioFilterForm, EditarUsuarioForm
from .models import Usuario


class Nuevo(CreateView):
    template_name = 'usuarios/nuevo.html'
    model = Usuario
    form_class = FormUsuario
    success_url = reverse_lazy('inicio')

    def get_context_data(self, **kwargs):
        ctx = super(Nuevo, self).get_context_data(**kwargs)
        ctx["titulo"] = "Nuevo registro"
        ctx["subtitulo"] = "Registro"
        return ctx


class UsuarioDetalles(DetailView):
    model = Usuario
    template_name = 'usuarios/detalle.html'
    context_object_name = 'usuario'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        ctx = super(UsuarioDetalles, self).get_context_data(**kwargs)
        ctx["titulo"] = "Detalles del Usuario"
        ctx["subtitulo"] = "Detalles"
        return ctx


class Lista(ListView):
    template_name = 'usuarios/lista.html'
    model = Usuario
    context_object_name = 'usuario'
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('q', '')  # 'q' es el nombre del campo del formulario
        if search_query:
            # Filtrar por nombre o apellido
            queryset = queryset.filter(
                Q(first_name__icontains=search_query) |
                Q(last_name__icontains=search_query)
            )
        return queryset
    
    def get_context_data(self, **kwargs):
        ctx = super(Lista, self).get_context_data(**kwargs)
        ctx["titulo"] = "Lista de Usuarios"
        ctx["subtitulo"] = "Lista de Usuarios"
        ctx['formulario_buscador'] = UsuarioFilterForm(self.request.GET or None)
        return ctx


def buscar_usuarios(request):
    query = request.GET.get('q', '')
    resultados = Usuario.objects.filter(
        Q(first_name__icontains=query) |
        Q(last_name__icontains=query)
    ).values('id', 'first_name', 'last_name')  # Devuelve solo los campos necesarios
    return JsonResponse(list(resultados), safe=False)


class UsuarioUpdate(LoginRequiredMixin, UpdateView):
    model = Usuario
    fields = ['first_name', 'last_name', 'dni', 'email', 'foto_perfil']
    template_name = 'usuarios/editar.html'
    context_object_name = 'usuario'

    def get_context_data(self, **kwargs):
        ctx = super(UsuarioUpdate, self).get_context_data(**kwargs)
        ctx["titulo"] = "Editar datos"
        return ctx
    
    def get_object(self, queryset=None):
        return self.request.user
    
    def get_success_url(self):
        return reverse('usuarios:detalle', kwargs={'id': self.request.user.pk})

    def form_valid(self, form):
        return super().form_valid(form)


User = get_user_model()

class AdminUserListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Usuario
    template_name = 'usuarios/admin_user_list.html'
    context_object_name = 'usuarios'
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('q')
        if search_query:
            queryset = queryset.filter(
                Q(first_name__icontains=search_query) | 
                Q(last_name__icontains=search_query)
            )
        return queryset

    def test_func(self):
        user = self.request.user
        return user.is_superuser or user.groups.filter(name='Administradores').exists()


    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        user = self.request.user
        ctx['es_admin'] = user.is_superuser or user.groups.filter(name='Administradores').exists()
        ctx['formulario_buscador'] = UsuarioFilterForm(self.request.GET or None)
        ctx["titulo"] = "Administración de Usuarios"
        ctx["subtitulo"] = "Administración"
        return ctx


@user_passes_test(lambda u: u.is_superuser or u.groups.filter(name='Administradores').exists())
def toggle_user_active(request, user_id):
    usuario = get_object_or_404(Usuario, id=user_id)
    usuario.is_active = not usuario.is_active
    usuario.save()
    estado = "activado" if usuario.is_active else "desactivado"
    messages.success(request, f"El usuario {usuario} ha sido {estado}.")
    return redirect('usuarios:admin_user_list')


class EditarUsuarioView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Usuario
    form_class = EditarUsuarioForm
    template_name = 'usuarios/admin_user_edit.html'

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.groups.filter(name='Administradores').exists()

    def get_success_url(self):
        return reverse('usuarios:admin_user_list')


class DetalleUsuarioView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Usuario
    template_name = 'usuarios/admin_user_detail.html'
    context_object_name = 'usuario'

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.groups.filter(name='Administradores').exists()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        cuenta = getattr(self.object, 'cuenta', None)  # Obtener la cuenta del usuario
        ctx['cuenta'] = cuenta
        ctx["titulo"] = "Detalles de la Cuenta"
        ctx["subtitulo"] = "Detalles"

        # Obtener todas las transacciones relacionadas (emitidas y recibidas)
        if cuenta:
            transacciones_emitidas = cuenta.transacciones_emitidas.all()
            transacciones_recibidas = cuenta.transacciones_recibidas.all()

            transacciones = transacciones_emitidas.union(transacciones_recibidas).order_by('-fecha')

            # Pagina las transacciones
            paginator = Paginator(transacciones, 5)  # Cambia '5' por el número de elementos por página
            page_number = self.request.GET.get('page')
            page_obj = paginator.get_page(page_number)

            ctx['transacciones'] = page_obj  # Lista paginada
            ctx['is_paginated'] = page_obj.has_other_pages()  # Indica si hay más páginas
            ctx['paginator'] = paginator  # Objeto paginador
            ctx['page_obj'] = page_obj  # Página actual
        else:
            ctx['transacciones'] = []
            ctx['is_paginated'] = False

        return ctx

src/templates/usuarios/admin_user_detail.html
{% extends "base/base.html" %}
{% load custom_filters %}

{% block title_block %}
        Detalles del Usuario
{% endblock title_block %}

{% block css_extras %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock css_extras %}

{% block content %}
<div class="app-content d-flex justify-content-center">
	<div class="col-md-10">
		<div class="card card-primary card-outline mb-4">
            
            <div class="card-header">
                <h5>Usuario: <strong>{{ usuario.get_full_name }}</strong></h5>
                <h5>Saldo: <strong>{{ cuenta.saldo|format_currency }}</strong></h5>
            </div>

            <!-- Contenido principal -->
            <div class="card-body">
                <h5>Transacciones</h5>
                <table class="table table-bordered table-hover" id="resultado-tabla">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Tipo</th>
                            <th>Monto</th>
                            <th>Motivo</th>
                            <th>Fecha</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for transaccion in transacciones %}
                        <tr>
                            <td>{{ transaccion.id }}</td>
                            <td>
                                {% if transaccion.tipo == "ingreso" %}
                                    <span class="badge bg-success">Ingreso</span>
                                {% else %}
                                    <span class="badge bg-primary">Transferencia</span>
                                {% endif %}
                            </td>                    
                            <td>{{ transaccion.monto|format_currency }}</td>
                            <td>{{ transaccion.motivo }}</td>
                            <td>{{ transaccion.fecha|date:"d M Y, H:i" }}</td>
                        </tr>
                        {% empty %}
                        <tr class="table-warning">
                            <td colspan="6" class="text-center">No hay transacciones relacionadas.</td>
                        </tr>                
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- Paginación -->
            <div class="d-flex justify-content-center">
                {% include "includes/paginacion.html" %}
            </div>
        
        </div>
    </div>
</div>
{% endblock %}

src/templates/usuarios/admin_user_edit.html
{% extends "base/base.html" %}

{% block title_block %}
        Editar Usuario
{% endblock title_block %}

{% block css_extras %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock css_extras %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h4>Editar Usuario</h4>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Guardar cambios</button>
        </form>
    </div>
</div>
{% endblock %}

src/templates/usuarios/admin_user_list.html
{% extends "base/base.html" %}

{% block title_block %}
        Administración de Usuarios
{% endblock title_block %}

{% block css_extras %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock css_extras %}

{% block content %}
<div class="app-content d-flex justify-content-center">
	<div class="col-md-10">
		<div class="card card-primary card-outline mb-4">

            <div class="card-header">
				<h4 class="card-title">Buscador</h4>
				<div class="card-tools">
					<form id="buscador-form" method="get" class="form-inline d-flex align-items-center">
						{{ formulario_buscador.q }}
						<button type="button" id="buscar-btn" class="btn btn-primary ml-2 bi bi-search"></button>
					</form>
				</div>
			</div>

            <!-- Contenido principal -->
            <div class="card-body">
                <table class="table table-bordered table-hover" id="resultado-tabla">
                    <thead>
                        <tr>
                            <th class="text-center">ID</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>DNI</th>
                            <th>Correo</th>
                            <th>Estado</th>
                            <th>Admin</th>
                            <th class="text-center">Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for usuario in usuarios %}
                            <tr>
                                <td class="text-center">{{ usuario.id }}</td>
                                <td>{{ usuario.first_name|default:'-' }}</td>
                                <td >{{ usuario.last_name|default:'-' }}</td>
                                <td >{{ usuario.dni|default:'-' }}</td>
                                <td>{{ usuario.email }}</td>
                                <td>
                                    {% if usuario.is_active %}
                                    <span class="badge bg-success">Activo</span>
                                    {% else %}
                                    <span class="badge bg-danger">Inactivo</span>
                                    {% endif %}
                                </td>
                                <td >{{ usuario.es_admin|default:'-' }}</td>
                                <td class="text-center">
                                    <a href="{% url 'usuarios:toggle_user_active' usuario.id %}" 
                                        class="btn btn-sm {% if usuario.is_active %}btn-danger{% else %}btn-success{% endif %}" 
                                        title="{% if usuario.is_active %}Desactivar{% else %}Activar{% endif %}">
                                        <i class="bi {% if usuario.is_active %}bi-person-x{% else %}bi-person-check{% endif %}"></i>
                                    </a>
                                    <a href="{% url 'usuarios:editar_usuario' usuario.id %}" class="btn btn-sm btn-success" title="Editar">
                                        <i class="bi bi-pencil"></i>
                                    </a>
                                    
                                    <a href="{% url 'usuarios:detalle_usuario' usuario.id %}" class="btn btn-sm btn-primary" title="Detalle"><i class="bi bi-info-circle"></i></a>
                                    
                                    <a href="#" class="btn btn-sm btn-danger" title="Eliminar"><i class="bi bi-trash"></i></a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="4" class="text-center">No se encontraron resultados</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <!-- Paginación -->
            <div class="d-flex justify-content-center">
                {% include "includes/paginacion.html" %}
            </div>

        </div>
    </div>
</div>
{% endblock %}

src/templates/usuarios/detalle.html
{% extends "base/base.html" %}

{% block title_block %}
        Detalles del Usario
{% endblock title_block %}

{% block content %}
<div class="app-content d-flex justify-content-center">
    <div class="col-md-6">
        <div class="card card-primary card-outline mb-4">

            <div class="card-body">
                <p><strong>Usuario:</strong> {{ usuario.username }}</p>
                <p><strong>Nombre:</strong> {{ usuario.first_name }}</p>
                <p><strong>Apellido:</strong> {{ usuario.last_name }}</p>
                <p><strong>Email:</strong> {{ usuario.email }}</p>
                <p><strong>DNI:</strong> {{ usuario.dni }}</p>
            </div>

            <div class="card-footer d-flex justify-content-end">
                <a href="{% url 'usuarios:editar' %}" class="btn btn-danger">Editar</a>
                <a href="{% url 'inicio' %}" class="btn btn-primary">Volver</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/templates/usuarios/editar.html
{% extends 'base/base.html' %}

{% block title_block %}
    Editar
{% endblock title_block %}

{% block css_extras %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock css_extras %}

{% block content %}
    <div class="app-content d-flex justify-content-center">
        <div class="col-md-6">
            <div class="card card-primary card-outline mb-4">
                <div class="card-header">
                    <div class="card-title">Detalle de la Vacuna</div>
                </div>
                {% include 'includes/forms_errors.html '%}
                
                {% if form.errors %}
                    <div class="alert alert-danger">
                        <ul>
                            {% for field, errors in form.errors.items %}
                                <li>{{ field }}: {{ errors|join:", " }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                
                <form method="post" enctype="multipart/form-data">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                
                    <div class="card-footer d-flex">
                        <button type="submit" class="btn btn-primary">
                            <i class="fas fa-save"></i> Guardar
                        </button>
                        <a href="{% url 'usuarios:detalle' usuario.id %}" class="btn btn-secondary">
                            <i class="fa-solid fa-rotate-left"></i> Volver
                        </a>
                    </div>
                </form>

            </div>
        </div>
    </div>
{% endblock content %}

src/templates/usuarios/lista.html
{% extends "base/base.html" %}

{% block title_block %}
        Lista de Usuarios
{% endblock title_block %}

{% block css_extras %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock css_extras %}

{% block content %}
<div class="app-content d-flex justify-content-center">
	<div class="col-md-10">
		<div class="card card-primary card-outline mb-4">
			
			<!-- Encabezado principal -->
			<div class="card-header d-flex justify-content-between align-items-center">
				<h4 class="card-title" style="flex-grow: 1;">Agregar Usuario</h4>
				<a href="{% url 'usuarios:nuevo' %}" class="btn btn-primary">Nuevo  <i class="bi bi-person-plus-fill"></i></a>
			</div>
			
			<!-- Buscador -->
			<div class="card-header">
				<h4 class="card-title">Buscador</h4>
				<div class="card-tools">
					<form id="buscador-form" method="get" class="form-inline d-flex align-items-center">
						{{ formulario_buscador.q }}
						<button type="button" id="buscar-btn" class="btn btn-primary ml-2 bi bi-search"></button>
					</form>
				</div>
			</div>

			<!-- Contenido principal -->
			<div class="card-body">
				<table class="table table-bordered table-hover" id="resultado-tabla">
					<thead>
						<tr>
							<th class="text-center">ID</th>
							<th>Nombre</th>
							<th>Apellido</th>
							<th>DNI</th>
							<th>Admin</th>
							<th class="text-center">Opciones</th>
						</tr>
					</thead>
					<tbody>
						{% for us in usuario %}
							<tr>
								<td class="text-center">{{ us.id }}</td>
								<td>{{ us.first_name|default:'-' }}</td>
								<td >{{ us.last_name|default:'-' }}</td>
								<td >{{ us.dni|default:'-' }}</td>
								<td >{{ us.es_admin|default:'-' }}</td>
								<td class="text-center">
									<a href="#" class="btn btn-sm btn-primary" title="Detalle"><i class="bi bi-info-circle"></i></a>
									<a href="#" class="btn btn-sm btn-success" title="Editar"><i class="bi bi-pencil"></i></a>
									<a href="#" class="btn btn-sm btn-danger" title="Eliminar"><i class="bi bi-trash"></i></a>
								</td>
							</tr>
						{% empty %}
							<tr>
								<td colspan="4" class="text-center">No se encontraron resultados</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>

			<!-- Paginación -->
			<div class="d-flex justify-content-center">
				{% include "includes/paginacion.html" %}
			</div>
			
		</div>
	</div>
</div>

<script>
    document.getElementById('buscar-btn').addEventListener('click', function() {
        const form = document.getElementById('buscador-form');
        const query = form.querySelector('input[name="q"]').value;

        fetch(`/ruta-del-endpoint-de-busqueda/?q=${query}`)
            .then(response => response.json())
            .then(data => {
                const tbody = document.querySelector('#resultado-tabla tbody');
                tbody.innerHTML = ''; // Limpia los resultados anteriores

                if (data.length === 0) {
                    tbody.innerHTML = `
                        <tr>
                            <td colspan="4" class="text-center">No se encontraron resultados</td>
                        </tr>`;
                } else {
                    data.forEach(item => {
                        const row = `
                            <tr>
                                <td class="text-center">${item.id}</td>
                                <td>${item.first_name}</td>
                                <td class="text-center">${item.last_name}</td>
                                <td class="text-center">
                                    <a href="#" class="btn btn-sm btn-info" title="Detalle"><i class="fas fa-eye"></i></a>
                                    <a href="#" class="btn btn-sm btn-warning" title="Editar"><i class="fas fa-pen"></i></a>
                                    <a href="#" class="btn btn-sm btn-danger" title="Eliminar"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>`;
                        tbody.innerHTML += row;
                    });
                }
            })
            .catch(error => {
                console.error('Error al realizar la búsqueda:', error);
            });
    });
</script>

{% endblock content %}

src/templates/usuarios/nuevo.html
{% extends 'base/base.html' %}

{% block title_block %}
        Nuevo Usuario
{% endblock title_block %}

{% block css_extras %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock css_extras %}

{% block content %}
    <div class="app-content d-flex justify-content-center">
        <div class="col-md-6">
            <div class="card card-primary card-outline mb-4">

                <div class="card-header">
                    <div class="card-title">Agregar Nuevo Usuario</div>
                </div>

                <form method="post">{% csrf_token %}
                    <div class="card-body">
                        {% include 'includes/forms_errors.html' %}

                        {% include 'includes/forms.html' %}
                    </div>

                    <div class="card-footer d-flex ">
                        <button type="submit" class="btn btn-primary"><i class="fa-solid fa-save"></i> Guardar</button>
                        <a href="{% url 'inicio' %}" class="btn btn-secundary"><i class="fa-solid fa-xmark"></i> Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}