src/apps/cuentas/urls.py
from django.urls import path

from . import views

app_name = 'cuentas'


urlpatterns = [
    path('nuevo/', views.Nuevo.as_view(), name='nuevo'),
    path('detalle/', views.CuentaDetalles.as_view(), name='detalle'),
    path('cuenta/', views.IngresoDineroView.as_view(), name='ingresar_dinero'),
    path('cuentas_frecuentes/agregar/', views.AgregarCuentaFrecuente.as_view(), name='agregar_cuenta_frecuente'),
    path('cuentas_frecuentes/', views.ListaCuentasFrecuentes.as_view(), name='lista_cuentas_frecuentes'),
    path('cuentas-frecuentes/eliminar/<int:pk>/', views.EliminarCuentaFrecuente.as_view(), name='eliminar_cuenta_frecuente'),
]

src/apps/usuarios/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'


urlpatterns = [
    path('nuevo/', views.Nuevo.as_view(), name='nuevo'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('usuario/<int:id>/', views.UsuarioDetalles.as_view(), name='detalle'),
    path('usuario/editar/', views.UsuarioUpdate.as_view(), name='editar'),

    path('buscar/', views.buscar_usuarios, name='buscar_usuarios'),
    path('admin/usuarios/', views.AdminUserListView.as_view(), name='admin_user_list'),
    path('admin/<int:user_id>/toggle-active/', views.toggle_user_active, name='toggle_user_active'),
    path('admin/<int:pk>/editar/', views.EditarUsuarioView.as_view(), name='editar_usuario'),
    path('admin/<int:pk>/detalle/', views.DetalleUsuarioView.as_view(), name='detalle_usuario'),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as views_django
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.BaseTemplateView.as_view(), name='inicio'),

    path('login/', views.LoginTempletaView.as_view(), name='login'),
    path('logout/', views_django.logout_then_login, name='logout'),

    path('cuentas/', include('apps.cuentas.urls')),
    path('motivos/', include('apps.motivos.urls')),
    path('transacciones/', include('apps.transacciones.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/cuentas/models.py
from django.conf import settings
from django.db import models

from apps.usuarios.models import Usuario


ESTADO_CHOICES = [
        (True, 'Activo'),
        (False, 'Inactivo')
]


class Cuenta(models.Model):
	id = models.BigAutoField(primary_key=True)
	saldo = models.DecimalField(max_digits=12, decimal_places=2, default=0)
	estado = models.BooleanField(choices=ESTADO_CHOICES, default=True)
	usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.id} - {self.usuario}'


class CuentaFrecuente(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    cuenta = models.ForeignKey(Cuenta, on_delete=models.CASCADE)
    alias = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        unique_together = ('usuario', 'cuenta')

    def __str__(self):
        return f'{self.usuario.username} - {self.cuenta.usuario.username} (Frecuente)'

src/apps/cuentas/forms.py
from django import forms

from .models import Cuenta, CuentaFrecuente


class FormCuenta(forms.ModelForm):
    class Meta:
        model = Cuenta
        fields = ['saldo', 'estado']


class IngresoDineroForm(forms.ModelForm):
    cantidad = forms.DecimalField(
        max_digits=12, decimal_places=2,
        label='Cantidad a ingresar',
        min_value=0, initial=0)

    class Meta:
        model = Cuenta
        fields = ['cantidad']


class CuentaFrecuenteForm(forms.ModelForm):
    class Meta:
        model = CuentaFrecuente
        fields = ['cuenta', 'alias']

    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['cuenta'].queryset = Cuenta.objects.exclude(usuario=user)

src/apps/cuentas/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy, reverse

from .forms import FormCuenta, IngresoDineroForm, CuentaFrecuenteForm
from .models import Cuenta, CuentaFrecuente

from apps.transacciones.models import Transaccion
from apps.motivos.models import Motivo

class Nuevo(LoginRequiredMixin, CreateView):
    template_name = 'cuentas/nuevo.html'
    model = Cuenta
    form_class = FormCuenta
    success_url = reverse_lazy('inicio')

    def get_context_data(self, **kwargs):
        ctx = super(Nuevo, self).get_context_data(**kwargs)
        ctx["titulo"] = "Nueva cuenta"
        ctx["subtitulo"] = "Cuenta"
        return ctx
    
    def form_valid(self, form):
        if Cuenta.objects.filter(usuario=self.request.user).exists():
            form.add_error(None, 'El usuario ya tiene una cuenta asociada.')
            return self.form_invalid(form)
        form.instance.usuario = self.request.user
        return super(Nuevo, self).form_valid(form)


class CuentaDetalles(DetailView):
    model = Cuenta
    template_name = 'cuentas/detalle.html'
    context_object_name = 'cuenta'
    
    def get_object(self, queryset=None):
        return self.request.user.cuenta

    def get_context_data(self, **kwargs):
        ctx = super(CuentaDetalles, self).get_context_data(**kwargs)
        ctx["titulo"] = "Cuenta"
        ctx["subtitulo"] = "Detalles"
        return ctx


class IngresoDineroView(LoginRequiredMixin, UpdateView):
    model = Cuenta
    form_class = IngresoDineroForm
    template_name = 'cuentas/ingreso_dinero.html'
    
    def form_valid(self, form):
        cuenta = form.save(commit=False)
        cantidad = form.cleaned_data['cantidad']
        cuenta.saldo += cantidad
        cuenta.save()

        # Registrar el ingreso como una transacción
        motivo = Motivo.objects.get(descripcion="Ingreso de dinero")

        Transaccion.objects.create(
            tipo='ingreso',
            receptor=cuenta,
            monto=cantidad,
            motivo=motivo
        )

        return super().form_valid(form)

    def get_object(self, queryset=None):
        return self.request.user.cuenta
    
    def get_success_url(self):
        return reverse('cuentas:detalle')
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["titulo"] = "Cuenta"
        ctx["subtitulo"] = "Ingresar Dinero"
        return ctx
    

class AgregarCuentaFrecuente(LoginRequiredMixin, CreateView):
    model = CuentaFrecuente
    form_class = CuentaFrecuenteForm
    template_name = 'cuentas/agregar_cuenta_frecuente.html'
    success_url = reverse_lazy('cuentas:lista_cuentas_frecuentes')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        # Verificar duplicados
        if CuentaFrecuente.objects.filter(usuario=self.request.user, cuenta=form.cleaned_data['cuenta']).exists():
            form.add_error('cuenta', 'Esta cuenta ya está en tu lista de frecuentes.')
            return self.form_invalid(form)

        form.instance.usuario = self.request.user
        return super().form_valid(form)


class ListaCuentasFrecuentes(LoginRequiredMixin, ListView):
    model = CuentaFrecuente
    template_name = 'cuentas/lista_cuenta_frecuente.html'
    context_object_name = 'cuentas_frecuentes'

    def get_queryset(self):
        return CuentaFrecuente.objects.filter(usuario=self.request.user)


class EliminarCuentaFrecuente(LoginRequiredMixin, DeleteView):
    model = CuentaFrecuente
    template_name = 'cuentas/eliminar_cuenta_frecuente.html'
    success_url = reverse_lazy('cuentas:lista_cuentas_frecuentes')

    def get_queryset(self):
        # Asegurarse de que el usuario solo pueda eliminar sus propias cuentas frecuentes
        return CuentaFrecuente.objects.filter(usuario=self.request.user)

src/templates/cuentas/agregar_cuenta_frecuente.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container">
    <h1>{{ titulo }}</h1>
    <h2>{{ subtitulo }}</h2>

    <form method="post">
        {% csrf_token %}

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Agregar</button>
        </form>

        <!-- <div class="form-group">
            {{ form.cuenta.label_tag }}<br>
            {{ form.cuenta }}
        </div>
        
        <div class="form-group">
            {{ form.alias.label_tag }}<br>
            {{ form.alias }}
        </div>
        
        <button type="submit" class="btn btn-primary">Guardar como frecuente</button> -->
        <a href="{% url 'cuentas:lista_cuentas_frecuentes' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

src/templates/cuentas/detalle.html
{% extends "base/base.html" %}
{% load custom_filters %}

{% block title_block %}
    Detalles de la Cuenta
{% endblock title_block %}

{% block content %}
<div class="app-content d-flex justify-content-center align-items-center" style="height: 100h;">
    <div class="col-md-6">
        <div class="card card-primary card-outline shadow">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h3 class="card-title">Detalles de la Cuenta</h3>
            </div>
            <div class="card-body">
                <p><strong>Saldo:</strong> {{ cuenta.saldo|format_currency }}</p>
                <p>
                    <strong>Estado:</strong>
                    {% if cuenta.estado %}
                        <span class="text-success">Activa</span>
                    {% else %}
                        <span class="text-danger">Inactiva</span>
                    {% endif %}
                </p>
                
                <div class="d-flex justify-content-end">
                    <a href="{% url 'cuentas:ingresar_dinero' %}" class="btn btn-primary">Ingresar dinero</a>
                    <a href="{% url 'usuarios:detalle' user.id %}" class="btn btn-secondary">Volver</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/templates/cuentas/eliminar_cuenta_frecuente.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Eliminar Cuenta Frecuente</h2>
<p>¿Estás seguro de que quieres eliminar esta cuenta frecuente?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'cuentas:lista_cuentas_frecuentes' %}" class="btn btn-secondary">Cancelar</a>
</form>
{% endblock content %}

src/templates/cuentas/ingreso_dinero.html
{% extends 'base/base.html' %}

{% block title_block %}
    Ingresar Dinero
{% endblock title_block %}

{% block content %}
<div class="app-content d-flex justify-content-center align-items-center" style="height: 100h;">
    <div class="col-md-6">
        <div class="card card-primary card-outline shadow">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h3 class="card-title">Ingresar Dinero</h3>
                
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary">
                            <i class="fas fa-save"></i> Guardar
                        </button>
                        <a href="{% url 'cuentas:detalle' %}" class="btn btn-secondary btn-sm">
                            <i class="fa-solid fa-rotate-left"></i> Volver
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/templates/cuentas/lista_cuenta_frecuente.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Mis Cuentas Frecuentes</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Alias</th>
            <th>Usuario</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for cuenta in cuentas_frecuentes %}
        <tr>
            <td>{{ cuenta.alias }}</td>
            <td>{{ cuenta.cuenta.usuario.username }}</td>
            <td>
                <a href="{% url 'cuentas:eliminar_cuenta_frecuente' cuenta.pk %}" class="btn btn-danger">Eliminar</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">No tienes cuentas frecuentes aún.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'cuentas:agregar_cuenta_frecuente' %}" class="btn btn-primary">Agregar nueva cuenta</a>
{% endblock %}

src/templates/cuentas/nuevo.html
{% extends 'base/base.html' %}

{% block title_block %}
        Nueva Cuenta
{% endblock title_block %}

{% block css_extras %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock css_extras %}

{% block content %}
    <div class="app-content d-flex justify-content-center">
        <div class="col-md-6">
            <div class="card card-primary card-outline mb-4">

                <div class="card-header">
                    <div class="card-title">Asociar Nueva Cuenta</div>
                </div>

                <form method="post">{% csrf_token %}
                    <div class="card-body">
                        {% include 'includes/forms_errors.html' %}

                        {% include 'includes/forms.html' %}
                    </div>

                    <div class="card-footer d-flex ">
                        <button type="submit" class="btn btn-success"><i class="fa-solid fa-save"></i> Guardar</button>
                        <a href="{% url 'inicio' %}" class="btn btn-primary"><i class="fa-solid fa-xmark"></i> Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}